=== ggntju/LPP-LPC-data-format/lpp-data-schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "required": [
        "ch_0_gain",
        "ch_1_gain",
        "ch_2_gain",
        "datablock_info",
        "datablock_sum",
        "layer_index",
        "layer_sum",
        "reserved_key"
    ],
    "properties": {
        "layer_sum": {
            "type": "integer"
        },
        "layer_index": {
            "type": "integer"
        },
        "datablock_sum": {
            "type": "integer"
        },
        "reserved_key": {
            "type": "string"
        },
        "ch_0_gain": {
            "type": "integer"
        },
        "ch_1_gain": {
            "type": "integer"
        },
        "ch_2_gain": {
            "type": "integer"
        },
        "datablock_info": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "datablock_index": {
                        "type": "integer"
                    },
                    "datablock_name": {
                        "type": "string"
                    },
                    "datablock_type": {
                        "type": "integer"
                    },
                    "skywriting_flag": {
                        "type": "integer"
                    },
                    "scan_speed": {
                        "type": "number"
                    },
                    "laser_power": {
                        "type": "number"
                    },
                    "datablock_data_sum": {
                        "type": "integer"
                    },
                    "reserved_key": {
                        "type": "string"
                    },
                    "datablock_data": {
                        "type": "array",
                        "items": {
                            "type": "array",
                            "items": {
                                "anyOf": [
                                    {
                                        "type": "array",
                                        "items": {
                                            "type": "integer"
                                        }
                                    },
                                    {
                                        "type": "integer"
                                    }
                                ]
                            }
                        }
                    }
                },
                "required": [
                    "datablock_data",
                    "datablock_data_sum",
                    "datablock_index",
                    "datablock_name",
                    "datablock_type",
                    "laser_power",
                    "reserved_key",
                    "scan_speed",
                    "skywriting_flag"
                ]
            }
        }
    }
}

=== ggntju/LPP-LPC-data-format/lpp-example.json
{
	"layer_sum": 50,
	"layer_index": 0,
	"datablock_sum":3,
	"reserved_key":"reserved_value",
	"ch_0_gain": 0,
	"ch_1_gain": 0,
	"ch_2_gain": 0,
	"datablock_info":[
		{
			"datablock_index":0,
			"datablock_name": "datablock_0",
			"datablock_type":1,
			"skywriting_flag": 1,
			"scan_speed":500.0,
			"laser_power":50.0,
			"datablock_data_sum":5,
			"reserved_key":"reserved_value",
			"datablock_data":[
				[11,25,15,21],
				[12,24,14,22],
				[13,23,13,23],
				[14,22,12,24],
				[15,21,11,25]
			]
		},
		{
			"datablock_index":1,
			"datablock_name": "datablock_1",
			"datablock_type":1,
			"skywriting_flag": 0,
			"scan_speed":600.0,
			"laser_power":70.0,
			"datablock_data_sum":3,
			"reserved_key":"reserved_value",
			"datablock_data":[
				[11,23,13,21],
				[12,22,12,22],
				[13,21,11,23]
			]
		},
		{
			"datablock_index":2,
			"datablock_name": "datablock_2",
			"datablock_type":3,
			"skywriting_flag": 1,
			"scan_speed":700.0,
			"laser_power":60.0,
			"datablock_data_sum":3,
			"reserved_key":"reserved_value",
			"datablock_data":[
				[
					[11,21],
					[12,22],
					[13,23]
				],
				[
					[14,24],
					[15,25]
				],
				[
					[16,26],
					[17,27]
				]
			]
		}
	]
}
